spring:
  application:
    name: crudOperation

  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=1h
#  datasource:
#    url: jdbc:h2:file:./data/bankingdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/crud
    username: postgres
    password: N@zaby
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # options: none, validate, update, create, create-drop
    show-sql: true

  jackson:
    mapper:
      sort-properties-alphabetically: false

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#  logging:
#    level:
#      org.springframework.ws.server.MessageTracing: TRACE
#      org.springframework.ws.client.MessageTracing: TRACE